services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XmKesearchRemote\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Xima\XmKesearchRemote\Command\FetchContentCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'ke_search:fetch-remotes'
        schedulable: true

  Xima\XmKesearchRemote\Indexer\RemoteIndexer:
    public: true
